spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: user
    url: jdbc:postgresql://localhost:5555/pizza-store
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: db/changelog/main-changelog.xml
server:
  port: 9090

store:
  app:
    secret: YUyf6UG3IhhoGIYUt9yIoh2IiojpoOtr
    expirationMs: 600000